--[[
	Exemple Structure for entity:
	EntityName = {
		Image: string, "rbxasset://",
		Rarity: string, "Common" 
		
		-- Optional parameters
		Size: Vector3, -- Size of the hitbox for the entity
		Spawnable: boolean, -- Defaults to false, makes a brainrot spawn on conveyor
		RequiresGroup: boolean, -- Defaults to false, makes brainrot claimable only if player is in group
		NormalHint: string, -- Defaults to nil, basic hint given in the index without paying robux
		BetterHint: string, -- Defaults to nil, advanced hint given in the index after paying robux
	}
]]

local EntityData = {
	
	-- Locked Door Entities

	["Six Seven"] = {
		Image = "rbxassetid://102578009544702",
		Rarity = "Secret",
		Size = Vector3.new(5, 5, 5),
		NormalHint = "Just by joining the group",
		BetterHint = "Just by joining the group",
	},
	
	-- Entities around the map
	["Bombardino Oldrilo"] = {
		Image = "rbxassetid://136743589042611",
		Rarity = "Epic",
		Size = Vector3.new(5, 5, 5),
	},
	["Lionel Cactuseli"] = {
		Image = "rbxassetid://101434028990823",
		Rarity = "Epic",
		Spawnable = true,
		Size = Vector3.new(5, 5, 5),
		NormalHint = "In a tree",
		BetterHint = "In an apple tree",
	},
	["Brr Brr Patapim"] = {
		Image = "rbxassetid://112998403627717",
		Rarity = "Epic",
		Size = Vector3.new(5, 5, 5),
		NormalHint = "In an apple tree",
		BetterHint = "In an apple tree in the corner of the map",
	},
	["Tralalero Tralaold"] = {
		Image = "rbxassetid://126633146363178",
		Rarity = "Legendary",
		Size = Vector3.new(5, 5, 5),
		NormalHint = "Behind a board",
		BetterHint = "Behind a leaderboard",
	},
	["Brr es Teh Oldpum"] = {
		Image = "rbxassetid://105232070185914",
		Rarity = "Legendary",
		Size = Vector3.new(5, 5, 5),
		NormalHint = "On an island",
		BetterHint = "On a floating island",
	},
	["Swag Soda"] = {
		Image = "rbxassetid://138799438313457",
		Rarity = "Mythic",
		NormalHint = "On an island",
		BetterHint = "On an island with a floating sea",
		Size = Vector3.new(5, 5, 5),
	},
	["Chef Crabracadabra"] = {
		Image = "rbxassetid://113426363966093",
		Rarity = "Legendary",
		Size = Vector3.new(5, 5, 5),
		NormalHint = "In the sky",
		BetterHint = "Climb the bamboo that is on the map",
        Spawnable = true,
	},
	["The Old Bros"] = {
		Image = "rbxassetid://126374147399157",
		Rarity = "Legendary",
		NormalHint = "It opens with 2 people",
		BetterHint = "The door is on top of a base and opens with 2 people",
		Size = Vector3.new(5, 5, 5),
	},
	["Brr Dicus Bombicus"] = {
		Image = "rbxassetid://73478006934524",
		Rarity = "Epic",
		NormalHint = "Inside a base",
		BetterHint = "Inside a base that has 2 floors",
		Size = Vector3.new(5, 5, 5),
	},
	["Dul Dul Dul Old"] = {
		Image = "rbxassetid://110750468689629",
		Rarity = "Epic",
		NormalHint = "Pass the obby",
		BetterHint = "Pass the obby of a floating island",
		Size = Vector3.new(5, 5, 5),
	},
	["Old Pakrahmatmamat"] = {
		Image = "rbxassetid://117105789262797",
		Rarity = "Epic",
		NormalHint = "Pass the obby",
		BetterHint = "Pass the pencil obby that's in the corner of the map",
		Size = Vector3.new(5, 5, 5),
	},
	["Old Pakrahmatina"] = {
		Image = "rbxassetid://105069081480496",
		Rarity = "Epic",
		NormalHint = "Pass the obby",
		BetterHint = "Pass the pencil obby that's in the corner of the map",
		Size = Vector3.new(5, 5, 5),
	},
	["Esok Sekolah"] = {
		Image = "rbxassetid://91486101671278",
		Rarity = "Secret",
		NormalHint = "Find the small house",
		BetterHint = "The small house is next to an apple tree.",
		Size = Vector3.new(5, 5, 5),
	},
	["The Old Combination"] = {
		Image = "rbxassetid://93881978796637",
		Rarity = "Legendary",
		NormalHint = "Not everything is inside the map.",
		BetterHint = "Fall off the edge and follow the outer wall.",
		Size = Vector3.new(5, 5, 5),
	},	
	["Centrucci Nuclucci"] = {
		Image = "rbxassetid://71742977617236",
		Rarity = "Legendary",
		NormalHint = "Inside a radioactive base",
		BetterHint = "Enter the two-story radioactive base, enter through the back window",
		Size = Vector3.new(5, 5, 5),
	},	
	["Job Job Old"] = {
		Image = "rbxassetid://75666640729633",
		Rarity = "Legendary",
		NormalHint = "Behind a base",
		BetterHint = "Behind a base that is on a floating island",
		Size = Vector3.new(5, 5, 5),
	},	
	["Rhino Toasterino"] = {
		Image = "rbxassetid://140545828502960",
		Rarity = "Legendary",
		NormalHint = "Pass the floating obby!",
		BetterHint = "Pass the floating obby! It's at the top of the map",
		Size = Vector3.new(5, 5, 5),
	},	
	["Garama and Madungdung"] = {
		Image = "rbxassetid://97575802534495",
		Rarity = "Legendary",
		NormalHint = "Say the name of this Brainrot in the chat!",
		BetterHint = "Say the name of this Brainrot in the chat, and a door will open in the corner of the map.",
		Size = Vector3.new(5, 5, 5),
	},	
	["Cerberus"] = {
		Image = "rbxassetid://73732988142879",
		Rarity = "Legendary",
		NormalHint = "Find the code numbers to open the door!!",
		BetterHint = "The code is 9914",
		Size = Vector3.new(5, 5, 5),
	},	
	["Odin Din Dun Old"] = {
		Image = "rbxassetid://121731576937131",
		Rarity = "Legendary",
		NormalHint = "Find the 5 kg dumbbell",
		BetterHint = "The dumbbell is above the yellow door of the Garama and Madungdung",
		Size = Vector3.new(5, 5, 5),
	},	
	["Graipuss Medussi"] = {
		Image = "rbxassetid://70831081529935",
		Rarity = "Mythic",
		NormalHint = "At sea",
		BetterHint = "In the sea of ​​a floating island",
		Size = Vector3.new(5, 5, 5),
	},	
	["Karker Kar Kur Old"] = {
		Image = "rbxassetid://120334574806240",
		Rarity = "Mythic",
		NormalHint = "In a blue chair",
		BetterHint = "Touch the blue chair that is on a floating island",
		Size = Vector3.new(5, 5, 5),
	},	
	["Burbaloni Luliloli"] = {
		Image = "rbxassetid://124790012916555",
		Rarity = "Secret",
		NormalHint = "Find the coconut",
		BetterHint = "The coconut is on a floating island next to a palm tree",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Pot Oldspot"] = {
		Image = "rbxassetid://113783141402853",
		Rarity = "Secret",
		NormalHint = "On an invisible wall of an obby",
		BetterHint = "Behind an invisible wall in the hamburger puzzle obby",
		Size = Vector3.new(5, 5, 5),
	},
	["Crabbo Limonetta"] = {
		Image = "rbxassetid://93478895493614",
		Rarity = "Secret",
		NormalHint = "It can only be obtained in Lucky Block.",
		BetterHint = "It can only be obtained in Lucky Block.",
		Size = Vector3.new(10, 10, 10),
	},
	["Vaquita Saturno"] = {
		Image = "rbxassetid://96011662642632",
		Rarity = "Secret",
		NormalHint = "Jump on the trampolines",
		BetterHint = "Jump over the trampolines to the left",
		Size = Vector3.new(5, 5, 5),
	},	
	["Ancient Dragon Canelloni"] = {
		Image = "rbxassetid://134415668825716",
		Rarity = "Secret",
		NormalHint = "Jump on the trampolines",
		BetterHint = "Jump over the trampolines to the right",
		Size = Vector3.new(5, 5, 5),
	},
	["Old Strawberry Elephant"] = {
		Image = "rbxassetid://71399838774518",
		Rarity = "Secret",
		NormalHint = "Find and click on the strawberry",
		BetterHint = "Find and click on the strawberry that is inside a 2-story base on the ceiling",
		Size = Vector3.new(5, 5, 5),
	},
	["Granchiello Spiritell"] = {
		Image = "rbxassetid://83605479287356",
		Rarity = "Secret",
		NormalHint = "Find the radio",
		BetterHint = "The radio is behind a base that's in the corner of the map.",
		Size = Vector3.new(5, 5, 5),
	},

	-- Spawnables
	["Oldini Noobini"] = {
		Image = "rbxassetid://124218694999238",
		Rarity = "Common",
		NormalHint = "I'm surprised you didn't find me!",
		BetterHint = "I'm walking",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Ancient Gangster"] = {
		Image = "rbxassetid://78501702512837",
		Rarity = "Common",
		NormalHint = "Behind a green block",
		BetterHint = "Behind the green block of the Bombardino Cocodrilo",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Fluriflura"] = {
		Image = "rbxassetid://102068567705008",
		Rarity = "Uncommon",
		NormalHint = "Above a base",
		BetterHint = "On top of a 2-story base",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Trippi Troppini"] = {
		Image = "rbxassetid://78508558786166",
		Rarity = "Uncommon",
		NormalHint = "Look up",
		BetterHint = "Climb the ladder that is in the middle of the map",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Salamino Penguino"] = {
		Image = "rbxassetid://105946855576978",
		Rarity = "Uncommon",
		NormalHint = "Look up",
		BetterHint = "Climb the ladder that is in the middle of the map",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Chimpazini Oldnini"] = {
		Image = "rbxassetid://120346587212350",
		Rarity = "Rare",
		NormalHint = "Inside a base",
		BetterHint = "Inside a 2-story base",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Boneca Ambalabu"] = {
		Image = "rbxassetid://70833356499183",
		Rarity = "Rare",
		NormalHint = "Above the...",
		BetterHint = "On top of a stick",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Lirili Larila"] = {
		Image = "rbxassetid://138481319279506",
		Rarity = "Rare",
		NormalHint = "Abaft",
		BetterHint = "Behind a 1-story base",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Matteo"] = {
		Image = "rbxassetid://100248000429620",
		Rarity = "Rare",
		NormalHint = "Above the...",
		BetterHint = "At the top of a tunnel",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Blueberrini Octopusini"] = {
		Image = "rbxassetid://89360193657646",
		Rarity = "Epic",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Ballerino Lolo"] = {
		Image = "rbxassetid://89425644987759",
		Rarity = "Epic",
		NormalHint = "On a 2-story base",
		BetterHint = "On a 2-story base located on a floating island",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Trulimero Trulichima"] = {
		Image = "rbxassetid://107964358510418",
		Rarity = "Epic",
		NormalHint = "Above the...",
		BetterHint = "On top of a stick",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Sigma Boy"] = {
		Image = "rbxassetid://76907885966817",
		Rarity = "Epic",
		NormalHint = "Above",
		BetterHint = "Up the walls",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Ballerina Oldita"] = {
		Image = "rbxassetid://138387495183471",
		Rarity = "Epic",
		NormalHint = "Inside a base",
		BetterHint = "Inside a 2-story base",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Glorbo Fruttodrillo"] = {
		Image = "rbxassetid://96885026792301",
		Rarity = "Epic",
		NormalHint = "Not everything important is up above, sometimes you have to look down.",
		BetterHint = "It's not on the surface it's hidden under the main platform.",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Picchone Machina"] = {
		Image = "rbxassetid://105748454623097",
		Rarity = "Epic",
		NormalHint = "Sometimes you have to look up.",
		BetterHint = "On top of a 2-story base",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Bambu Sahur"] = {
		Image = "rbxassetid://102225512012854",
		Rarity = "Legendary",
		NormalHint = "Bamboooo",
		BetterHint = "Climb the bamboo tree that's in the middle of the map",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Chilin Chili"] = {
		Image = "rbxassetid://125497689781345",
		Rarity = "Legendary",
		NormalHint = "Look for an island separate from the main map.",
		BetterHint = "Behind an island separate from the main map",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Caballo Virtuold"] = {
		Image = "rbxassetid://116401183011340",
		Rarity = "Mythic",
		NormalHint = "In a maze",
		BetterHint = "In a labyrinth, to enter it, touch a small house",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Bandito Oldito"] = {
		Image = "rbxassetid://87473076211359",
		Rarity = "Mythic",
		NormalHint = "Not everything important is up above, sometimes you have to look down.",
		BetterHint = "It's not on the surface it's hidden under the main platform.",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Bombombini Gusini"] = {
		Image = "rbxassetid://108370164049803",
		Rarity = "Mythic",
		NormalHint = "Up in a tree",
		BetterHint = "Up on a flying tree",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Ganganzelli Trulala"] = {
		Image = "rbxassetid://74059454339186",
		Rarity = "Mythic",
		NormalHint = "Behind a lucky block",
		BetterHint = "Behind a lucky block of mustache",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Nuclearo Dinosauriold"] = {
		Image = "rbxassetid://94211806200886",
		Rarity = "Mythic",
		NormalHint = "On a floating island",
		BetterHint = "On a floating island, look down from it",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},	
	["Old Cappuccino"] = {
		Image = "rbxassetid://96190136082169",
		Rarity = "Mythic",
		NormalHint = "Behind something yellow",
		BetterHint = "Behind the garama and madungdung puzzle",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Agarrini La Palini"] = {
		Image = "rbxassetid://129034087199075",
		Rarity = "Mythic",
		NormalHint = "Inside a sky base",
		BetterHint = "Inside a 2-story base located on a floating island",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Orcaleold"] = {
		Image = "rbxassetid://123124316303786",
		Rarity = "Mythic",
		NormalHint = "Above a sky base",
		BetterHint = "Above a 2-story base located on a floating island",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Trenostruzzo Turbo 4000"] = {
		Image = "rbxassetid://74115416040196",
		Rarity = "Secret",
		NormalHint = "Tire",
		BetterHint = "The tire is under a classroom chair",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	["Bulbito Bandito Traktorito"] = {
		Image = "rbxassetid://97085553014742",
		Rarity = "Secret",
		NormalHint = "In a maze",
		BetterHint = "In a labyrinth, to enter it, touch a small house",
		Size = Vector3.new(5, 5, 5),
		Spawnable = true,
	},
	
	-- Vending machine Entities
	["Hydra Dragon"] = {
	Image = "rbxassetid://77154866534075",
		Rarity = "Secret",
		Size = Vector3.new(5, 5, 5),
	},
	
	-- Luckyblock entities
	["Mythic Lucky Block"] = {
		Image = "rbxassetid://122921349633528",
		Rarity = "Common",
		NormalHint = "Only in lucky block",
		BetterHint = "Only in lucky block yellow",
		Size = Vector3.new(5, 5, 5),
	},
	
	["Brainrot God Lucky Block"] = {
		Image = "rbxassetid://92308716948665",
		Rarity = "Rare",
		NormalHint = "Only in lucky block",
		BetterHint = "Only in lucky block yellow",
		Size = Vector3.new(5, 5, 5),
	},
	
	["Secret Lucky Block"] = {
		Image = "rbxassetid://124271019295116",
		Rarity = "Epic",
		NormalHint = "Only in lucky block",
		BetterHint = "Only in lucky block yellow",
		Size = Vector3.new(5, 5, 5),
	},
	
	["Admin Lucky Block"] = {
		Image = "rbxassetid://103395486952738",
		Rarity = "Legendary",
		NormalHint = "Only in lucky block",
		BetterHint = "Only in lucky block yellow",
		Size = Vector3.new(5, 5, 5),
	},
	
	["Los Lucky Blocks"] = {
		Image = "rbxassetid://108586213035177",
		Rarity = "Secret",
		NormalHint = "Only in lucky block",
		BetterHint = "Only in lucky block yellow",
		Size = Vector3.new(5, 5, 5),
	},

-- Mostacho Lucky Blocks 
	["Guerreiro Digitold"] = {
		Image = "rbxassetid://129320218202084",
		Rarity = "Epic",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Mastodontico Telepiedone "] = {
	    Image = "rbxassetid://76773821566885",
		Rarity = "Rare",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Chicleterold Bicicleteiro"] = {
		Image = "rbxassetid://115621678145565",
		Rarity = "Epic",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Blackhole Goat"] = {
		Image = "rbxassetid://126162479495315",
		Rarity = "Legendary",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Ketupat Kepat"] = {
		Image = "rbxassetid://79050969022195",
		Rarity = "Mythic",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Miau"] = {
		Image = "rbxassetid://95132940840708",
		Rarity = "Secret",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
	["Arcadopus"] = {
		Image = "rbxassetid://139923942401316",
		Rarity = "Secret",
		NormalHint = "Only in Mostacho lucky block",
		BetterHint = "Only in lucky block mostacho",
		Size = Vector3.new(5, 5, 5),
	},
}
return EntityData