--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["AppNet"] = {} }
elseif not _G.__ZAP["AppNet"] then
	_G.__ZAP["AppNet"] = {}
elseif _G.__ZAP["AppNet"]["APP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of APP, remote_folder of AppNet and the version of {_G.__ZAP["AppNet"]["APP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["AppNet"]["APP"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		HotbarSetSlot = table.freeze({
			On = noop
		}),
		HotbarSetEquipped = table.freeze({
			On = noop
		}),
		HotbarRequestToggle = table.freeze({
			Fire = noop
		}),
		HotbarClearSlot = table.freeze({
			On = noop
		}),
		GetServerTime = table.freeze({
			Call = noop
		}),
		CombatRequestParry = table.freeze({
			Fire = noop
		}),
		CombatRequestAttack = table.freeze({
			Fire = noop
		}),
	}) :: Events
end
local remotes = ReplicatedStorage:WaitForChild("AppNet")

local reliable = remotes:WaitForChild("APP_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected APP_RELIABLE to be a RemoteEvent")


local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(4)
local reliable_event_queue: { [number]: { any } } = table.create(4)
local function_call_id = 0
reliable_events[0] = {}
reliable_event_queue[0] = {}
reliable_events[1] = {}
reliable_event_queue[1] = {}
reliable_events[2] = {}
reliable_event_queue[2] = {}
reliable_event_queue[3] = table.create(255)
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- HotbarSetSlot
			local value, value2, value3, value4
			value = buffer.readu8(incoming_buff, read(1))
			local len_1 = buffer.readu16(incoming_buff, read(2))
			value2 = buffer.readstring(incoming_buff, read(len_1), len_1)
			assert(utf8.len(value2) ~= nil, "value is not valid utf-8")
			local len_2 = buffer.readu16(incoming_buff, read(2))
			value3 = buffer.readstring(incoming_buff, read(len_2), len_2)
			assert(utf8.len(value3) ~= nil, "value is not valid utf-8")
			local len_3 = buffer.readu16(incoming_buff, read(2))
			value4 = buffer.readstring(incoming_buff, read(len_3), len_3)
			assert(utf8.len(value4) ~= nil, "value is not valid utf-8")
			if reliable_events[0][1] then
				for _, cb in reliable_events[0] do
					task.spawn(cb, value, value2, value3, value4)
				end
			else
				table.insert(reliable_event_queue[0], { value, value2, value3, value4 })
				if #reliable_event_queue[0] > 64 then
					warn(`[ZAP] {#reliable_event_queue[0]} events in queue for HotbarSetSlot. Did you forget to attach a listener?`)
				end
			end
		elseif id == 1 then -- HotbarSetEquipped
			local value, value2
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			value = buffer.readu8(incoming_buff, read(1))
			value2 = bit32.btest(bool_1, 0b0000000000000001)
			if reliable_events[1][1] then
				for _, cb in reliable_events[1] do
					task.spawn(cb, value, value2)
				end
			else
				table.insert(reliable_event_queue[1], { value, value2 })
				if #reliable_event_queue[1] > 64 then
					warn(`[ZAP] {#reliable_event_queue[1]} events in queue for HotbarSetEquipped. Did you forget to attach a listener?`)
				end
			end
		elseif id == 2 then -- HotbarClearSlot
			local value
			value = buffer.readu8(incoming_buff, read(1))
			if reliable_events[2][1] then
				for _, cb in reliable_events[2] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[2], value)
				if #reliable_event_queue[2] > 64 then
					warn(`[ZAP] {#reliable_event_queue[2]} events in queue for HotbarClearSlot. Did you forget to attach a listener?`)
				end
			end
		elseif id == 3 then -- GetServerTime
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			value = buffer.readf64(incoming_buff, read(8))
			local thread = reliable_event_queue[3][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[3][call_id] = nil
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	HotbarSetSlot = {
		On = function(Callback: (slot: (number), uid: (string), toolName: (string), textureId: (string)) -> ())
			table.insert(reliable_events[0], Callback)
			for _, value in reliable_event_queue[0] do
				task.spawn(Callback, unpack(value))
			end
			reliable_event_queue[0] = {}
			return function()
				table.remove(reliable_events[0], table.find(reliable_events[0], Callback))
			end
		end,
	},
	HotbarSetEquipped = {
		On = function(Callback: (slot: (number), isEquipped: (boolean)) -> ())
			table.insert(reliable_events[1], Callback)
			for _, value in reliable_event_queue[1] do
				task.spawn(Callback, unpack(value))
			end
			reliable_event_queue[1] = {}
			return function()
				table.remove(reliable_events[1], table.find(reliable_events[1], Callback))
			end
		end,
	},
	HotbarRequestToggle = {
		Fire = function(slot: (number))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
		end,
	},
	HotbarClearSlot = {
		On = function(Callback: (slot: (number)) -> ())
			table.insert(reliable_events[2], Callback)
			for _, value in reliable_event_queue[2] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[2] = {}
			return function()
				table.remove(reliable_events[2], table.find(reliable_events[2], Callback))
			end
		end,
	},
	GetServerTime = {
		Call = function(): ((number))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[3][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			reliable_event_queue[3][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	CombatRequestParry = {
		Fire = function()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
		end,
	},
	CombatRequestAttack = {
		Fire = function(comboIndex: (number))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, comboIndex)
		end,
	},
}
type Events = typeof(returns)
return returns
