--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Server generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

if RunService:IsClient() then
	error("Cannot use the server module on the client!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["AppNet"] = {} }
elseif not _G.__ZAP["AppNet"] then
	_G.__ZAP["AppNet"] = {}
elseif _G.__ZAP["AppNet"]["APP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of APP, remote_folder of AppNet and the version of {_G.__ZAP["AppNet"]["APP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["AppNet"]["APP"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
	})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		HotbarSetSlot = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		HotbarSetEquipped = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		HotbarRequestToggle = table.freeze({
			On = noop
		}),
		HotbarClearSlot = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		GetServerTime = table.freeze({
			SetCallback = noop
		}),
		CombatRequestParry = table.freeze({
			On = noop
		}),
		CombatRequestParryEnd = table.freeze({
			On = noop
		}),
		CombatRequestAttack = table.freeze({
			On = noop
		}),
	}) :: Events
end

local remotes = ReplicatedStorage:FindFirstChild("AppNet")
if remotes == nil then
	remotes = Instance.new("Folder")
	remotes.Name = "AppNet"
	remotes.Parent = ReplicatedStorage
end

local reliable = remotes:FindFirstChild("APP_RELIABLE")
if reliable == nil then
	reliable = Instance.new("RemoteEvent")
	reliable.Name = "APP_RELIABLE"
	reliable.Parent = remotes
end

local player_map = {}

local function load_player(player: Player)
	if player_map[player] then
		load(player_map[player])
	else
		load_empty()
	end
end

Players.PlayerRemoving:Connect(function(player)
	player_map[player] = nil
end)

local function SendEvents()
	for player, outgoing in player_map do
		if outgoing.used > 0 then
			local buff = buffer.create(outgoing.used)
			buffer.copy(buff, 0, outgoing.buff, 0, outgoing.used)

			reliable:FireClient(player, buff, outgoing.inst)

			outgoing.buff = buffer.create(64)
			outgoing.used = 0
			outgoing.size = 64
			table.clear(outgoing.inst)
		end
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(5)
reliable_events[0] = {}
reliable_events[2] = {}
reliable_events[1] = {}
reliable_events[4] = {}
reliable.OnServerEvent:Connect(function(player, buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- HotbarRequestToggle
			local value
			value = buffer.readu8(incoming_buff, read(1))
			for _, cb in reliable_events[0] do
				task.spawn(cb, player, value)
			end
		elseif id == 2 then -- CombatRequestParry
			local value
			for _, cb in reliable_events[2] do
				task.spawn(cb, player, value)
			end
		elseif id == 4 then -- CombatRequestParryEnd
			local value
			for _, cb in reliable_events[4] do
				task.spawn(cb, player, value)
			end
		elseif id == 1 then -- CombatRequestAttack
			local value
			value = buffer.readu8(incoming_buff, read(1))
			for _, cb in reliable_events[1] do
				task.spawn(cb, player, value)
			end
		elseif id == 3 then -- GetServerTime
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[3] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[3](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 3)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, ret_1)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	HotbarSetSlot = {
		Fire = function(Player: Player, slot: (number), uid: (string), toolName: (string), textureId: (string))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local len_1 = #uid
			assert(utf8.len(uid) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_1)
			alloc(len_1)
			buffer.writestring(outgoing_buff, outgoing_apos, uid, len_1)
			local len_2 = #toolName
			assert(utf8.len(toolName) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_2)
			alloc(len_2)
			buffer.writestring(outgoing_buff, outgoing_apos, toolName, len_2)
			local len_3 = #textureId
			assert(utf8.len(textureId) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_3)
			alloc(len_3)
			buffer.writestring(outgoing_buff, outgoing_apos, textureId, len_3)
			player_map[Player] = save()
		end,
		FireAll = function(slot: (number), uid: (string), toolName: (string), textureId: (string))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local len_4 = #uid
			assert(utf8.len(uid) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_4)
			alloc(len_4)
			buffer.writestring(outgoing_buff, outgoing_apos, uid, len_4)
			local len_5 = #toolName
			assert(utf8.len(toolName) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_5)
			alloc(len_5)
			buffer.writestring(outgoing_buff, outgoing_apos, toolName, len_5)
			local len_6 = #textureId
			assert(utf8.len(textureId) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_6)
			alloc(len_6)
			buffer.writestring(outgoing_buff, outgoing_apos, textureId, len_6)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, slot: (number), uid: (string), toolName: (string), textureId: (string))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local len_7 = #uid
			assert(utf8.len(uid) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_7)
			alloc(len_7)
			buffer.writestring(outgoing_buff, outgoing_apos, uid, len_7)
			local len_8 = #toolName
			assert(utf8.len(toolName) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_8)
			alloc(len_8)
			buffer.writestring(outgoing_buff, outgoing_apos, toolName, len_8)
			local len_9 = #textureId
			assert(utf8.len(textureId) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_9)
			alloc(len_9)
			buffer.writestring(outgoing_buff, outgoing_apos, textureId, len_9)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, slot: (number), uid: (string), toolName: (string), textureId: (string))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local len_10 = #uid
			assert(utf8.len(uid) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_10)
			alloc(len_10)
			buffer.writestring(outgoing_buff, outgoing_apos, uid, len_10)
			local len_11 = #toolName
			assert(utf8.len(toolName) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_11)
			alloc(len_11)
			buffer.writestring(outgoing_buff, outgoing_apos, toolName, len_11)
			local len_12 = #textureId
			assert(utf8.len(textureId) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
			alloc(len_12)
			buffer.writestring(outgoing_buff, outgoing_apos, textureId, len_12)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, slot: (number), uid: (string), toolName: (string), textureId: (string))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local len_13 = #uid
			assert(utf8.len(uid) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_13)
			alloc(len_13)
			buffer.writestring(outgoing_buff, outgoing_apos, uid, len_13)
			local len_14 = #toolName
			assert(utf8.len(toolName) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_14)
			alloc(len_14)
			buffer.writestring(outgoing_buff, outgoing_apos, toolName, len_14)
			local len_15 = #textureId
			assert(utf8.len(textureId) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_15)
			alloc(len_15)
			buffer.writestring(outgoing_buff, outgoing_apos, textureId, len_15)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	HotbarSetEquipped = {
		Fire = function(Player: Player, slot: (number), isEquipped: (boolean))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_1 = 0
			local bool_1_pos_1 = alloc(1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			if isEquipped then
				bool_1 = bit32.bor(bool_1, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_1_pos_1, bool_1)
			player_map[Player] = save()
		end,
		FireAll = function(slot: (number), isEquipped: (boolean))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_2 = 0
			local bool_2_pos_1 = alloc(1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			if isEquipped then
				bool_2 = bit32.bor(bool_2, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_2_pos_1, bool_2)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, slot: (number), isEquipped: (boolean))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_3 = 0
			local bool_3_pos_1 = alloc(1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			if isEquipped then
				bool_3 = bit32.bor(bool_3, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_3_pos_1, bool_3)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, slot: (number), isEquipped: (boolean))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_4 = 0
			local bool_4_pos_1 = alloc(1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			if isEquipped then
				bool_4 = bit32.bor(bool_4, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_4_pos_1, bool_4)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, slot: (number), isEquipped: (boolean))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_5 = 0
			local bool_5_pos_1 = alloc(1)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			if isEquipped then
				bool_5 = bit32.bor(bool_5, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_5_pos_1, bool_5)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	HotbarRequestToggle = {
		On = function(Callback: (Player: Player, slot: (number)) -> ()): () -> ()
			table.insert(reliable_events[0], Callback)
			return function()
				table.remove(reliable_events[0], table.find(reliable_events[0], Callback))
			end
		end,
	},
	HotbarClearSlot = {
		Fire = function(Player: Player, slot: (number))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			player_map[Player] = save()
		end,
		FireAll = function(slot: (number))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, slot: (number))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, slot: (number))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, slot: (number))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, slot)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	GetServerTime = {
		SetCallback = function(Callback: (Player: Player) -> ((number))): () -> ()
			reliable_events[3] = Callback
			return function()
				reliable_events[3] = nil
			end
		end,
	},
	CombatRequestParry = {
		On = function(Callback: (Player: Player) -> ()): () -> ()
			table.insert(reliable_events[2], Callback)
			return function()
				table.remove(reliable_events[2], table.find(reliable_events[2], Callback))
			end
		end,
	},
	CombatRequestParryEnd = {
		On = function(Callback: (Player: Player) -> ()): () -> ()
			table.insert(reliable_events[4], Callback)
			return function()
				table.remove(reliable_events[4], table.find(reliable_events[4], Callback))
			end
		end,
	},
	CombatRequestAttack = {
		On = function(Callback: (Player: Player, comboIndex: (number)) -> ()): () -> ()
			table.insert(reliable_events[1], Callback)
			return function()
				table.remove(reliable_events[1], table.find(reliable_events[1], Callback))
			end
		end,
	},
}
type Events = typeof(returns)
return returns
